# Generated by Django 2.2.19 on 2023-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0006_qr_qurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(help_text='Прикрепите картинку', upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='link',
            field=models.TextField(help_text='Введите текст поста', verbose_name='Ссылка'),
        ),
    ]
